### PR TITLE
Automated dependency upgrades

### PR DESCRIPTION
**Pull request by hc-github-team-secure-vault-ecosystem**
Full log: https://github.com/hashicorp/vault-plugin-auth-kerberos/actions/runs/10189637977

  IMPROVEMENTS:
* Updated dependencies:
   * `github.com/hashicorp/vault/api` v1.13.0 -> v1.14.0
   * `github.com/hashicorp/vault/sdk` v0.12.0 -> v0.13.0

### CODE REVIEW

**Comment by hc-github-team-secure-vault-core** [comment]
Vault CI check PR: https://github.com/hashicorp/vault/pull/23438

**Comment by hc-github-team-secure-vault-core** [comment]
Vault CI check PR: https://github.com/hashicorp/vault/pull/26723

**Comment by hc-github-team-secure-vault-core** [comment]
Vault CI check PR: https://github.com/hashicorp/vault/pull/26723

**Comment by hc-github-team-secure-vault-core** [comment]
Vault CI check PR: https://github.com/hashicorp/vault/pull/26723

**Comment by hc-github-team-secure-vault-core** [comment]
Vault CI check PR: https://github.com/hashicorp/vault/pull/26723

**Review by tvoran — APPROVED** [review]

**Pull request merged**
